
# ，，，。mismatch


content_relation0_list = [
    'unexpected global type',
    'divide by zero',
    'integer overflow',
    'integer representation too long',
    'malformed reference type',
    'wasm operand stack overflow',
    'invalid var_u32',
    'compiling function overran its stack height limit',
    'v128 value type requires simd feature',
    'type mismatch',
    'trailing bytes at end of section',
    'integer too large',
    'Invalid signed LEB encoding',
    'unsupported opcode fd',
    'unsupported opcode fc',
    'Unknown opcode',
    'unknown memory',
    'unknown table',
    'bulk memory support is not enabled',
    'multi-memory support is not enabled',
    'memory index reserved byte must be zero',
    'SIMD support is not enabled',
    'table index out of bounds',
    'illegal opcode',
    'Unexpected EOF',
    'expected data but found end of stream',
    'Mismatched memory alignment',
    'alignment too large',
    'alignment greater than natural alignment',
    'elemSegmentIndex must be less than module.elemSegments.size()',
    'operators remaining after end of function',
    'Invalid alignment',
    'alignment must not be larger than natural',
    'unsupported opcode',
    'section size mismatch',
    'Expected non-empty control stack',
    'stack was not empty at end of control structure',
    'invalid lane index',
    'local index out of bounds',
    'reference types support is not enabled',
    'unexpected end-of-file',
    'Invalid var_i32',
    'Invalid var_i64',
    'zero byte expected',
    'out of bounds memory access',
    'outOfBoundsMemoryAccess',
    'Unknown 0xfc subopcode',
    'memoryIndex must be less than module.memories.size',
    'exportIt.index must be less than module.memories.size',
    'function index out of bounds',
    'invalid function type',
    'Unknown 0xfd subopcode',
    'invalid local type',
    'depth must be less than controlStack',
    'validation failed: unknown label',
    'out of bounds table access',
    'locals exceed maximum',
    'outOfBoundsElemSegmentAccess',
    'tail calls support is not enabled',
    'multi-memory not enabled',
    'outOfBoundsTableAccess',
    'outOfBoundsDataSegmentAccess',
    'Unknown 0xfe subopcode',
    'type index out of bounds',
    'section overrun while parsing Wasm binary',
    'control frames remain at end of function',
    'section underrun while parsing Wasm binary',
    'call stack exhausted',
    'invalid function code size',
    'branch depth too large',
    'no compiler found for opcode',
    'no operation found for opcode',
    'unknown value_type',
    'invalid value type',
    'Invalid type',
    'malformed value type',
    'invalid result arity',
    'unreachable',
    'non-typed select operands must have the same numeric type',
    'Invalid unsigned LEB encoding',
    'typed select must have exactly one result',
    'invalid local count',
    'undeclared function reference',  # 
    'fast interpreter offset overflow',  # ,
    'unknown function',
    'functionIndex must be less than module.functions.size()',
    'unexpected end of section or function',
    'local count too large',
    'too many locals',
    'section contained more data than expected',
    'invalid reference type encoding',
    'end of code reached before end of function',
    '[trap] stack overflow',
    'invalid conversion to integer',
    'unknown error failed to compile fast jit function',
    'unsupported table element type: ExternRef',
    'cannot display funcref values',
    'uninitialized element',
    'unknown value type',
    'cannot display externref',
    'malformed export kind',
    'invalid export kind',
    'global index out of bounds',
    'invalid leading byte',
    'unknown data segment',
    'duplicate export name',
    'unexpected content after last section',
    'code section have inconsistent lengths',
    'incompatible import type',
    'WASM data stack underflow',
    'constant expression required: non-constant operator',
    'the result conversion is failed',
    'data count and data section have inconsistent lengths'
    
]
# unhandled SIGSEGVCall stack unknown function，
content_relation0_list = sorted(content_relation0_list, key=lambda x: len(x), reverse=True)
